### ISSUE TITLE
Get Status for create server return "succeeded" later that required

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/APIDocs#4] opened 2015-04-16 16:00 UTC
Steps:
1. Request creation of server with managed OS
2. Interatevelly call GetStatus method 

Actual result:
GetStatus return "succeeded" later that actually server build completed. And server is not available yet for operation execution.

Expected result:
GetStatus return "succeeded" and after that server is ready for execution of power operations.

**Comment by idrabenia** [comment] 2015-04-16 16:08
For instance this test code failes because after GetStatus return "succeeded" server is not ready and it is not possibile to execute delete operation for it.

```
@Test(enabled = false) // blocked by https://github.com/CenturyLinkCloud/APIDocs/issues/4
    public void testCreateWithManagedOS() {
        ServerMetadata newServer =
            serverService.create(anyServerConfig()
                .name("CMOS")
                .template(Template.refByOs()
                    .dataCenter(DataCenters.US_EAST_STERLING)
                    .type(RHEL)
                    .edition("6")
                    .architecture(x86_64)
                )
                .managedOs()
                .group(Group.refByName()
                    .name(DEFAULT_GROUP)
                    .dataCenter(DataCenters.US_EAST_STERLING)
                )
            )
            .waitUntilComplete()
            .getResult();

        assert !isNullOrEmpty(newServer.getId());

        cleanUpCreatedResources(newServer.asRefById());
    }

    void cleanUpCreatedResources(ServerRef newServer) {
        serverService
            .delete(newServer)
            .waitUntilComplete();
    }
```

**Comment by bryanfriedman** [comment] 2015-04-16 17:11
This is actually by design for Managed Servers. After the "success" status, a bunch of stuff is installed on the server before it is marked as active. Use the Get Server API call and check the status for "active" rather than "underConstruction".

**Closed by bryanfriedman** 2015-04-16 17:11 UTC
